name: code-style
run-name: ${{ github.actor }} has triggered Laravel Pint

on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: psr12

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Laravel Pint changes
