name: backend-tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wayfinder
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: wayfinder
      DB_USERNAME: root
      DB_PASSWORD: ""

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: xdebug

      - uses: actions/checkout@v4

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_ACTION_SSH_PRIVATE_KEY }}
          name: id_rsa_acquire_github
          config: ${{ vars.TEST_ACTION_SSH_CONFIG }}
          known_hosts: 'github.com'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Tests
        run: ./vendor/bin/pest
